### ISSUE TITLE
Lack of licensing

### ISSUE THREAD

**Issue by Ulferno** [ReAdminRBX/roblox-long-polling#4]
Hi.

I appreciate this code you've built and open-sourced, it's great.
I'd love to use it in my project, however this repository lacks a license (therefore it default's to the maintainer's exclusive copyright).

Could a license be added?

**Comment by mwalden2004** [comment]
https://github.com/ReAdminRBX/roblox-long-polling/blob/master/LICENSE.md

🆗 ✅ 

There you go!
