### ISSUE TITLE
Can't send table information

### ISSUE THREAD

**Issue by Laqota** [ReAdminRBX/roblox-long-polling#5]
I can't seem to send table information through it. Am I doing something wrong?

**Comment by zhiyan114** [comment]
Convert the table into json then send it.

**Comment by LocalSmail** [comment]
or you can just make it a string then send it afterwards convert it back into a json

**Comment by mwalden2004** [comment]
Right, you must convert the data into JSON as HTTP Service/this module does not do it for you.
