### ISSUE TITLE
Update library on npm and GitHub releases

### ISSUE THREAD

**Issue by axolotlmaid** [ReAdminRBX/roblox-long-polling#7]
@zhiyan114 submitted a pull request (#3) in June 2022 and got merged. On npm and GitHub releases, there hasn't been a new release since February 2022. I request that this library gets a new release to add typescript support.

**Comment by mwalden2004** [comment]
This is a fair request, forgive me, I have not gotten any notifications about this repository

**Comment by mwalden2004** [comment]
![image](https://github.com/ReAdminRBX/roblox-long-polling/assets/16482350/acc3e70f-f984-4bb5-a004-2af85eae34b4)
